### ISSUE TITLE
Adding icons(boxicons) in Nuxt.js in 2 steps.

### ISSUE THREAD

**Issue by dobbbri** [lusaxweb/vuesax-next#110]
1 - Install the boxicons package

 ``` 
$ npm install boxicons --save
```

2 - in nuxt.config.js add boxicons.min.css

``` 
css: ['vuesax/dist/vuesax.css', 'boxicons/css/boxicons.min.css'],  
```

finish!

**Comment by anandasansol** [comment]
I was not able to see the box icons after I setup a new project. Below steps fixed the issue:
I added 
`import 'boxicons/css/boxicons.min.css'` 
in my App.vue file and bang on 👍 Icons started appearing. I think this should be added in the documentation under "Getting Started"

**Comment by shift14wx** [comment]
@anandasansol that works, thanks!

**Comment by anandasansol** [comment]
> @anandasansol that works, thanks!

Cool.

**Comment by token-codeclouds** [comment]
tried above all solutions but didn't work for me
