### ISSUE TITLE
No url found for submodule path 'packages/docs/.vuepress/dist' in .gitmodules

### ISSUE THREAD

**Issue by zabihy** [lusaxweb/vuesax-next#113]
1. I tried to install repo by npm to test it in my project using this command: npm install https://github.com/lusaxweb/vuesax-next.git
2. I got this error: No url found for submodule path 'packages/docs/.vuepress/dist' in .gitmodules

**Comment by herynugroho** [comment]
you can try using this command: npm install vuesax@next

https://vuesax.com/docs/guide/gettingStarted.html

**Comment by zabihy** [comment]
> you can try using this command: npm install vuesax@next
> 
> https://vuesax.com/docs/guide/gettingStarted.html

thank you @herynugroho
