### ISSUE TITLE
icon not showing

### ISSUE THREAD

**Issue by FabienRakoto** [lusaxweb/vuesax-next#134]
hey guy how can i get the icon
<img width="1312" alt="Capture d’écran 2021-01-14 à 20 40 45" src="https://user-images.githubusercontent.com/31955628/104628066-d8662780-56a8-11eb-8795-5f37fdf8612b.png">

**Comment by ofeck21** [comment]
you can trying to install boxicons manually to solve it.
npm install boxicons 
and then 
import 'boxicons/css/boxicons.min.css'
on your app.js

**Comment by brdtheo** [comment]
install boxicons, since there are several ways to add it i'd recommend you to check https://boxicons.com/usage/
you will have all of the details there 👍🏻
