### ISSUE TITLE
website - dark theme - white on white

### ISSUE THREAD

**Issue by TCLNA** [lusaxweb/vuesax-next#136]
in https://vuesax.com/license/#plans, toggling dark theme is making text unreadable

![image](https://user-images.githubusercontent.com/32589981/104813802-bc2ecb80-580b-11eb-859e-bf70fb41a285.png)

tested on firefox and edge

**Comment by hartingsdev** [comment]
Same is true for Brave(Version 1.19.92 Chromium: 88.0.4324.152 (Official Build) (64-bit)) and Chrome (Version 88.0.4324.150 (Official Build) (64-bit))
