### ISSUE TITLE
How do I put two icons back and forth in the input tag?

### ISSUE THREAD

**Issue by ByeongUkChoi** [lusaxweb/vuesax-next#143]
vs-input tag has only one icon ?
```html
      <vs-input placeholder="Password">
        <template #icon>
          <i class="bx bx-lock"></i>
        </template
```
or
```html
      <vs-input icon-after placeholder="Password">
        <template #icon>
          <i class="bx bx-lock"></i>
        </template
```  
<br/>  

But I want to put two icons like this  
  
![image](https://user-images.githubusercontent.com/43606066/107145370-548c1c00-6984-11eb-8019-bf0cf36f5bb6.png)

Is it possible?

For example
```html
      <vs-input icon-both placeholder="Password">
        <template #icon>
          <i class="bx bx-lock"></i>
        </template
        <template #icon-after>
          <i class="bx bx-show-alt"></i>
        </template
```  

Thank you for your help in advance ;)

**Comment by brdtheo** [comment]
I don't think that it's possible since inputs have either `icon-before`or `icon-after` boolean. I guess putting both is not working ?

**Comment by ByeongUkChoi** [comment]
> I don't think that it's possible since inputs have either `icon-before`or `icon-after` boolean. I guess putting both is not working ?

I got it!
Merci beaucoup
