### ISSUE TITLE
<vs-dialog> tag does not working

### ISSUE THREAD

**Issue by muhhizbe** [lusaxweb/vuesax-next#15]
`<vs-button gradient warn @click="active=!active">
    Open Dialog
</ vs-button>  `    

`<vs-dialog overflow-hidden full-screen v-model="active">

        <template header>
          <h4 class="not-margin">Welcome to <b>Vuesax</b></h4>
        </template>
        <div class="con-form">
          <vs-input v-model="input1" placeholder="Email">
            <template #icon>
              @
            </template>
          </vs-input>
          <vs-input type="password" v-model="input2" placeholder="Password">
            <template #icon>
              <i class="bx bxs-lock"></i>
            </template>
          </vs-input>
          <div class="flex">
            <vs-checkbox v-model="checkbox1">Remember me</vs-checkbox>
            <a href="#">Forgot Password?</a>
          </div>
        </div>
        <template #footer>
          <div class="footer-dialog">
            <vs-button block>
              Sign In
            </vs-button>
            <div class="new">
              New Here? <a href="#">Create New Account</a>
            </div>
          </div>
        </template>

</vs-dialog>`
i implement this code from vuesax's v4 documentation to my project & i get a error message like this:

> [Vue warn]: Unknown custom element: <vs-dialog> - did you register the component correctly? For recursive components, make sure to provide the "name" option.   vue.js:634

how to fix it?

**Comment by luisDanielRoviraContreras** [comment]
In the code I do not see that you use the vs-dialog component, then verify that it is as in the example and if the problem persists, open it again
