### ISSUE TITLE
is https://vuesax.com/ Open-Source?

### ISSUE THREAD

**Issue by 0x77dev** [lusaxweb/vuesax-next#2]
is https://vuesax.com/ Open-Source?

**Comment by luisDanielRoviraContreras** [comment]
If you can see the code here https://github.com/lusaxweb/vuesax-next/tree/master/packages/docs

**Comment by oliviertassinari** [comment]
@0x77dev The license seems to be GPLv3, which is considered Open Source by the [OSI](https://opensource.org/licenses). The license is  summarized in https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3). How is it different from the MIT license? One example, you must disclose your sources:

> All code linked with GPL 3.0 source code must be disclosed under a GPL 3.0 compatible license.
