### ISSUE TITLE
Kindly apply patch for dialog

### ISSUE THREAD

**Issue by shivamguys** [lusaxweb/vuesax-next#20]
Appreciate your efforts team for bringing v4 and adding tons of features into it and making it stable.
Have limelight on isssue [https://github.com/lusaxweb/vuesax/issues/717](https://github.com/lusaxweb/vuesax/issues/717) related to **dialog dom hangs**

**Comment by luisDanielRoviraContreras** [comment]
Ready, the error is fixed

thanks for warning
