### ISSUE TITLE
Is this project still active.? Any words on v4.?

### ISSUE THREAD

**Issue by premdasvm** [lusaxweb/vuesax-next#225]

**Comment by adam-ali** [comment]
+1, love the look of it so far but dont want to add it to my project unless we have a stable release

**Comment by nimdeveloper** [comment]
Project is abandoned: https://github.com/lusaxweb/vuesax-next/issues/169#issuecomment-886166897

**Comment by nimdeveloper** [comment]
You can check this link maybe find alternative for this project: https://github.com/lusaxweb/vuesax-next/issues/161
