### ISSUE TITLE
Invalid documentation examples

### ISSUE THREAD

**Issue by decima** [lusaxweb/vuesax-next#29]
On the grid page, when checking examples on how to use responsive grids, the example is the following:
```
  <template>
    <div class="center">
      <vs-button active >Active</vs-button>
      <vs-button>Default</vs-button>
      <vs-button disabled >Disabled</vs-button>
    </div>
  </template>
```

The same append on almost every example of the page.

**Comment by luisDanielRoviraContreras** [comment]
the examples have already been changed to the real code

Thank you
