### ISSUE TITLE
Typo in getting started guide

### ISSUE THREAD

**Issue by abhishekashyap** [lusaxweb/vuesax-next#3]
Typo in the getting started page of the docs
[https://vuesax.com/docs/guide/gettingStarted.html]

**Comment by luisDanielRoviraContreras** [comment]
What is the mistake to fix it?

**Comment by abhishekashyap** [comment]
On #Uso page change Uso to Use. I have created a PR.

**Comment by BaroDevelopment** [comment]
> On #Uso page change Uso to Use. I have created a PR.

Change it to **Usage** and not Use lol
