### ISSUE TITLE
Warning on importing Vuesax

### ISSUE THREAD

**Issue by abhishekashyap** [lusaxweb/vuesax-next#6]
Could not find a declaration file for module 'vuesax'
// Warning encountered in vscode

npm version: 6.13.4
node version: v12.16.1
OS: macOS Catalina
Model: iMac (Retina 5K, 27-inch, 2019)

**Comment by luisDanielRoviraContreras** [comment]
This problem has already been fixed, it was due to an error compiling and the files were not uploaded to npm

**Comment by janiskemper** [comment]
I encountered the same issue. Could you please reopen?

npm version 6.13.7
vuesax version 3.11.13
Windows 10

**Comment by luisDanielRoviraContreras** [comment]
vuesax-next? npm i vuesax@next
