### ISSUE TITLE
duplicate :root in multiple locations in vuesax.css file

### ISSUE THREAD

**Issue by lly0414** [lusaxweb/vuesax-next#60]
There are 23 :root definitions in the vuesax.css file, but 22 of them are repeated. Does it have any special meaning?

**Comment by luisDanielRoviraContreras** [comment]
Thank you very much the problem was fixed and it will be uploaded in the next update

**Comment by luisDanielRoviraContreras** [comment]
https://github.com/lusaxweb/vuesax-next/releases/tag/4.0.1-alpha.25

**Comment by lly0414** [comment]
> https://github.com/lusaxweb/vuesax-next/releases/tag/4.0.1-alpha
👏
