### ISSUE TITLE
Missing VsLoading Background Color Template in Docs

### ISSUE THREAD

**Issue by DrCheddar** [lusaxweb/vuesax-next#61]
![image](https://user-images.githubusercontent.com/46302202/88482491-803b3d80-cf2f-11ea-8dde-555c5b2a85d5.png)

**Comment by luisDanielRoviraContreras** [comment]
thank you very much it was added in the next update

**Comment by luisDanielRoviraContreras** [comment]
https://github.com/lusaxweb/vuesax-next/releases/tag/4.0.1-alpha.25
