### ISSUE TITLE
Missing position-right prop for sidebar

### ISSUE THREAD

**Issue by moonkey124** [lusaxweb/vuesax-next#63]
It would be nice if you could position the sidebar to the right. Exactly how it worked in Vuesax 3

**Comment by luisDanielRoviraContreras** [comment]
thank you very much

Support was already added in the next update

**Comment by luisDanielRoviraContreras** [comment]
https://github.com/lusaxweb/vuesax-next/releases/tag/4.0.1-alpha.25
