### ISSUE TITLE
[Sidebar] - Having multiple scroll elements creates a page overflow

### ISSUE THREAD

**Issue by moonkey124** [lusaxweb/vuesax-next#64]
When there are more elements in the sidebar than the display is able to show it starts to scroll. This works, however it also adds an unnecessary overflow at the bottom. The attached gif demonstrates that you are able to scroll normally through your sidebar, however you can also scroll below the sidebar. 
![Sidebar](https://user-images.githubusercontent.com/23150076/88584734-68100f00-d052-11ea-9e29-be80b34a1f77.gif)

**Steps to Reproduce**
1. Create a sidebar.
2. Add multiple elements.
3. Resize your window so not all elements fit into it.

**Expected**
Only the sidebar should scroll.

**Result**
The sidebar does scroll however you can also scroll below it.

**Comment by moonkey124** [comment]
So I played a little bit more with it and got it working how I wanted it to be. I basically had to overwrite the position:
```
.vs-sidebar-content.absolute {
  position: fixed !important;
}
```
So I had to make it fixed, however I also know that this is definitely not a great solution. I am not very experienced with all of this. Feel free if the bevavior is as intended and close the issue.

**Comment by luisDanielRoviraContreras** [comment]
thank you very much

the default sidebar component has the position fixed

please remove the absolute property and try to see if it works as expected
