### ISSUE TITLE
Text not center

### ISSUE THREAD

**Issue by akirarika** [lusaxweb/vuesax-next#65]
Hello, first of all, thank you for creating this beautiful framework! 👍 

It's just that I had a little problem, in the select component, text **not center**

As shown in the figure:

![Snipaste_2020-07-30_12-21-26](https://user-images.githubusercontent.com/33272184/88880525-8b5bd980-d25f-11ea-812c-cc1de74f207a.png)

I noticed a line CSS,

```css
.vs-select__label: {
    top: 10px
}
```

After deleting it, the text becomes centered

I don't know if this is a feature or a bug,

but, thank you again for creating this beautiful framework!

**:3**

**Comment by luisDanielRoviraContreras** [comment]
thank you very much

fix it for the next update

**Comment by luisDanielRoviraContreras** [comment]
https://github.com/lusaxweb/vuesax-next/releases/tag/4.0.1-alpha.25
