### ISSUE TITLE
[Dialog] - Require callback to close

### ISSUE THREAD

**Issue by vk2r** [lusaxweb/vuesax-next#66]
I am currently developing an implementation of the dialogue and have encountered a problem. At the moment of closing the dialog, I would like to have a callback at the moment of closing it from the same close button, which has the dialog.
I think this requirement can be useful for many possible implementations of the dialog.

**Comment by luisDanielRoviraContreras** [comment]
solved

Thank you very much in the next update it will be uploaded

**Comment by luisDanielRoviraContreras** [comment]
https://github.com/lusaxweb/vuesax-next/releases/tag/4.0.1-alpha.25
