### ISSUE TITLE
[Select] - Filter errors "this.childOptions[this.hoverOption] is undefined" on enter press

### ISSUE THREAD

**Issue by DrCheddar** [lusaxweb/vuesax-next#74]
Steps to reproduce:

1. Use vs-select element with `filter` option like on https://vuesax.com/docs/components/Select.html#filter
2. Type a letter
3. Press enter
![image](https://user-images.githubusercontent.com/46302202/90259006-559a2180-de17-11ea-8a06-aa92324b8b43.png)

**Comment by luisDanielRoviraContreras** [comment]
Thank you very much for warning, it is already fixed

in the next update I upload it

**Comment by luisDanielRoviraContreras** [comment]
https://github.com/lusaxweb/vuesax-next/releases/tag/4.0.1-alpha.25
