### ISSUE TITLE
[sidebar] Not opening the group header

### ISSUE THREAD

**Issue by hsmfawaz** [lusaxweb/vuesax-next#79]
**Steps to Reproduce**
no steps required

**Expected**
the sidebar group " Coding" should be opened because the the sidebar selected item is one of the group items 

**Result**
only the sidebar-items get selected and the sidebar will not select the parent item if the select is subitem

**Testcase**
(fork this to get started)
https://codesandbox.io/s/vuesax-buttons-default-forked-6954k

**Comment by luisDanielRoviraContreras** [comment]
Thank you very much for warning, it has already been fixed and will be implemented in the next update

**Comment by luisDanielRoviraContreras** [comment]
https://github.com/lusaxweb/vuesax-next/releases/tag/4.0.1-alpha.25
