### ISSUE TITLE
Tooltip not getting destroyed upon page change 

### ISSUE THREAD

**Issue by GrimGraysamas** [lusaxweb/vuesax-next#82]
I use an interactive tooltip with a button to redirect to another page but when I do so, the tooltip is not destroyed and still appears on the next page. It ends up causing this error: 

TypeError: Failed to execute 'insertBefore' on 'Node': parameter 1 is not of type 'Node'.
    at insertBody (vuesax.js?574d:18277)
    at VueComponent.insertTooltip (vuesax.js?574d:22426)
    at VueComponent.eval (vuesax.js?574d:22457)
    at Array.eval (vue.common.dev.js?4650:1985)
    at flushCallbacks (vue.common.dev.js?4650:1911)

I am using nuxt in SPA mode

Has anyone figured out a solution or a work around ? Thank you for your help

**Comment by jonorozcoc** [comment]
> I use an interactive tooltip with a button to redirect to another page but when I do so, the tooltip is not destroyed and still appears on the next page. It ends up causing this error:
> 
> TypeError: Failed to execute 'insertBefore' on 'Node': parameter 1 is not of type 'Node'.
> at insertBody (vuesax.js?574d:18277)
> at VueComponent.insertTooltip (vuesax.js?574d:22426)
> at VueComponent.eval (vuesax.js?574d:22457)
> at Array.eval (vue.common.dev.js?4650:1985)
> at flushCallbacks (vue.common.dev.js?4650:1911)
> 
> I am using nuxt in SPA mode
> 
> Has anyone figured out a solution or a work around ? Thank you for your help

This is the solution I used in my project:

Creating a global navigation guard after route change that remove the tooltip html node

```
router.afterEach((to, from) => {
  document.body.removeChild(document.querySelector('.vs-tooltip'))
})
```

**Comment by luisDanielRoviraContreras** [comment]
Fixed for the next update, thank you very much for the contribution

**Comment by luisDanielRoviraContreras** [comment]
https://github.com/lusaxweb/vuesax-next/releases/tag/4.0.1-alpha.25
