### ISSUE TITLE
Radio not working at all

### ISSUE THREAD

**Issue by VagnerGon** [lusaxweb/vuesax-next#83]
**Steps to Reproduce**
no steps required

**Expected**
Radio box to select item

**Result**
v-model always get undefined

Testcase: Just try to select an option:

https://codesandbox.io/s/vuesax-buttons-default-forked-uwozr

P.S: Working on version 4 alpha

**Comment by samzhangjy** [comment]
Seems like you've added the wrong dep. You're using Vuesax 3.x in your project, but using it in a 4.x way. Editing the library's version to the latest (4.0.1-alpha.24) will help.

**Comment by VagnerGon** [comment]
Seems that the documentation is incorrect for version 3.x. Using vs-value worked
