### ISSUE TITLE
Buttons initial render bug

### ISSUE THREAD

**Issue by ayushsharma82** [lusaxweb/vuesax-next#86]
All Buttons initially render with their background as blue (primary color), and we can get a glimpse of them changing to their specified style as they render. ( for 0.1s ).

Possible improvements:
- Remove the base class which has the `background` set as blue
- Add only the relevant style/class so that components render directly to our specified style instead of jumping action seen right now.

**Comment by Ant-V** [comment]
This issue has the side-effect of not changing back to default (blue) color if you change the DOM and replace a previously "colored" button with a non-colored button. 
It keeps the color of the previous class.

As stated above, remove the background color from all base classes and add a "default" color option

**Comment by luisDanielRoviraContreras** [comment]
Thank you very much I will check to improve the theme of colors and rendering

**Comment by luisDanielRoviraContreras** [comment]
https://github.com/lusaxweb/vuesax-next/releases/tag/4.0.1-alpha.25
