### ISSUE TITLE
Hello! How to import vuesax font icon

### ISSUE THREAD

**Issue by buqiyuan** [lusaxweb/vuesax-next#9]
![image](https://user-images.githubusercontent.com/39730999/76134461-79339180-6059-11ea-894d-9790b57a08e1.png)
![image](https://user-images.githubusercontent.com/39730999/76134469-8badcb00-6059-11ea-82fe-5c3cb4eb7ee5.png)

**Comment by dalirnet** [comment]
[https://boxicons.com/usage/](boxicons)

```javascript
$ npm install boxicons --save
```
```javascript
import 'boxicons'
````

**Comment by 151409132** [comment]
Also need  **“main.js”** add to the  **"import 'boxicons/css/boxicons.min.css'"**
 this is my realized ~
not good english.... 0.0

**Comment by ByeongUkChoi** [comment]
> [https://boxicons.com/usage/](boxicons)
> 
> ```js
> $ npm install boxicons --save
> ```
> 
> ```js
> import 'boxicons'
> ```

install boxicons(npm install boxicons --save) and add this line
```js
import 'boxicons/css/boxicons.min.css'
```
