### ISSUE TITLE
Absurd Project Structure

### ISSUE THREAD

**Issue by ayushsharma82** [lusaxweb/vuesax-next#90]
With all due respect, this is not how we should structure repositories which contain NPM package.

Please add all vuesax 4.0 files in the default vuesax@next branch so that somebody who wants to clone the repository directly can do so in NPM without any hassle.

Keep this repository to host your docs. Make a separate repo for all the vuesax core functionality.

For Example, right now I can't even do this: `npm i ayushsharma82/vuesax-next` to test my changes.

**Comment by luisDanielRoviraContreras** [comment]
explain better what you mean to improve the structure

**Comment by ayushsharma82** [comment]
@luisDanielRoviraContreras , 
Right now, there is no way to get the source code 'only' and help it improve, we have to download whole vuesax 4.0 docs to review our bug fixes. 

As this is hosted on NPM, I suggest keeping Vuesax source files in this repository only. Documentation can be hosted on any other repository which will greatly help this project.

**Comment by ayushsharma82** [comment]
Or maybe it is because your vuesax@next branch is not publically available, which is a terrible decision.

**Comment by luisDanielRoviraContreras** [comment]
What do you mean by not having the source code? here is all the vuesax 4 code in which you can help and fix bugs
https://github.com/lusaxweb/vuesax-next/tree/master/packages/vuesax/src

**Comment by ayushsharma82** [comment]
@luisDanielRoviraContreras I think you are missing my point, Currently, the source code is deep inside the repository, It should be at the top level.

Reason:
**NPM allows us to install repositories directly from github** and we **can't** do like this: `npm i lusaxweb/vuesax-next`  , or in case I clone this repo to fix bugs, I **can't** do ` npm i ayushsharma82/vuesax-next`. It is something which is very serious as we all will have to depend on you creating a new release so that we can have our changes in our own project.

**Comment by luisDanielRoviraContreras** [comment]
https://github.com/nuxt/nuxt.js

so is this repository wrong too?

now the repositories are maintained by lerna and thus it is easier to manage each of the plugins of the ecosystem

**Comment by ayushsharma82** [comment]
It comes to the scope of the repository, Nuxt is a whole framework and Vuesax is just a component library, you can check their packages folder, It contains various small packages which contribute to the whole project. In this repository, all we need is a `/packages/vuesax` folder which has everything. 

Sadly, it's just making the project less developer-friendly. When all of the functionality is in a single folder, there is no point in using Lerna. Docs and Vuepress theme can be separated out.

**Comment by ayushsharma82** [comment]
The decision is yours, I felt it is convoluted when I wanted to check my changes in my own projects, and I could not install my cloned repository. I had to essentially wait for you to merge the pull request and create a release which is just delaying things.

If you are going to use Lerna then you can add a couple of points in the documentation:
1. How to Install cloned Vuesax repository as a package in a project?
2. Add a link to a sample ( glitch? ) page which contains all components for testing our changes.

**Comment by luisDanielRoviraContreras** [comment]
Thank you very much for the advice. I will improve the way to test the components and add documentation for those who want to help and how they can do it
