### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by luoxuhai** [lusaxweb/vuesax-next#96]
![image](https://user-images.githubusercontent.com/37284154/92739588-a0c03980-f3af-11ea-8b8f-e42e5a1506a2.png)

![image](https://user-images.githubusercontent.com/37284154/92740041-04e2fd80-f3b0-11ea-983e-34ab24ea1b2b.png)

- nuxt: 2.14.0
- vuesax: 4.0.1-alpha.24

**Comment by luisDanielRoviraContreras** [comment]
that is because nuxt tries to implement vuesax before being the DOM, the solution is to put vuesax only on the client side
https://nuxtjs.org/guide/plugins/#client-or-server-side-only
